<#include "../header.ftlh">

<h1>Добро пожаловать в увлекательный мир криптоанализа и стеганографии!</h1>
    
<p>Здесь вы окунетесь в захватывающий лабиринт шифров, тайных кодов и скрытых посланий. Наши интерактивные курсы не
    только познакомят вас с основами криптографии, но и научат расшифровывать самые разные шифры.</p>

<p>Мы предлагаем не просто уроки, а настоящее приключение, в котором раскроем перед вами тайны самых известных шифров и
    методов стеганографии. Давайте вместе отправимся в увлекательное путешествие по миру шифров и загадок!</p>

<p>Подготовьтесь к тому, чтобы раскрыть новые горизонты знаний и стать настоящим мастером криптоанализа и
    стеганографии. Начнем это увлекательное приключение прямо сейчас!</p>

<div style="display: flex; flex-direction: row; justify-content: space-around">
    <form action="/openCryptanalysisLevels" method="get">
        <button style="margin: 1rem; width: 50vh; border-radius: 30px" type="submit" class="btn btn-primary"><h1>
                Криптоанализ</h1></button>
    </form>
    <form action="/openSteganographyLevels" method="get">
        <button style="margin: 1rem; width: 50vh; border-radius: 30px" type="submit" class="btn btn-primary"><h1>
                Стеганография</h1></button>
    </form>
</div>

<#include "../footer.ftlh">